<?php

namespace Database\Seeders;

use App\Models\FactoryPartner;
use Illuminate\Database\Seeder;

class FactoryPartnerSeeder extends Seeder
{
    public function run(): void
    {
        $factories = [
            [
                'name' => 'Envoy Group',
                'category' => 'Woven',
                'specialization' => 'Woven tops and bottoms',
                'compliance' => true,
                'leed' => null,
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Windy Group',
                'category' => 'Woven',
                'specialization' => 'Shirts, blouses, dresses, skirts, trousers, shorts, outerwear and padded jackets',
                'compliance' => true,
                'leed' => null,
                'capacity' => 'Up to 4,500,000 pcs/month',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Vertex Group',
                'category' => 'Woven',
                'specialization' => 'Shirts, blouses, tops, skirts, dresses, schoolwear, joggers, trousers, boxers and chinos',
                'compliance' => true,
                'leed' => null,
                'capacity' => 'Approximately 1,500,000 pcs/month',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Aman Tex',
                'category' => 'Knit',
                'specialization' => 'T-shirts, printed tees, sweatshirts, hoodies, bomber jackets and childrenswear',
                'compliance' => true,
                'leed' => null,
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Divine Group',
                'category' => 'Knit',
                'specialization' => 'Menswear, womenswear, boys, girls and baby knit products',
                'compliance' => false,
                'leed' => null,
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Pioneer Knitwears',
                'category' => 'Sweater',
                'specialization' => 'Sweaters, gloves, caps, scarves, mittens and sleeping bags',
                'compliance' => false,
                'leed' => null,
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Energypac Fashion',
                'category' => 'Tailoring',
                'specialization' => 'Suits, coats, blazers, trousers and waistcoats',
                'compliance' => true,
                'leed' => null,
                'capacity' => '540,000 pcs/month',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Habitus Fashion Ltd.',
                'category' => 'Activewear',
                'specialization' => 'Tops, bottoms, jackets, T-shirts, polos, hoodies, sportswear, leggings and casualwear',
                'compliance' => true,
                'leed' => null,
                'capacity' => 'Current 1,000,000 pcs/month',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'ZNZ Company',
                'category' => 'Home Textile',
                'specialization' => 'Bedding, towels, duvet covers, pillow covers, bedspreads, cushions and table textiles',
                'compliance' => false,
                'leed' => null,
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Reaz Knitwear Ltd.',
                'category' => 'Knit',
                'specialization' => 'Mens, womens and childrens knit and woven garments',
                'compliance' => true,
                'leed' => null,
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Impress Fashion Ltd.',
                'category' => 'Woven',
                'specialization' => 'Casual shirts, dress shirts, ladies blouses, denim tops, sleepwear and shorts',
                'compliance' => true,
                'leed' => null,
                'capacity' => 'Approximately 650,000 pcs/month',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Bando Eco Apparels Ltd.',
                'category' => 'Woven',
                'specialization' => 'Mens and womens shirts, blouses, jackets, trousers, chinos and skirts',
                'compliance' => true,
                'leed' => null,
                'capacity' => 'Approximately 1,040,000 pcs/month',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Interstoff Group',
                'category' => 'Knit',
                'specialization' => 'Knit garments, fabric knitting, dyeing and printing',
                'compliance' => false,
                'leed' => null,
                'capacity' => 'Expansion target: 8,000,000 pcs/month',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'AKH Fashions Ltd.',
                'category' => 'Woven',
                'specialization' => 'Formal shirts, casual shirts, ladies blouses and school shirts',
                'compliance' => false,
                'leed' => null,
                'capacity' => '247,500 pcs/month',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Dhaka Garments & Washing',
                'category' => 'Woven',
                'specialization' => 'Denim jeans, shorts, jackets, trousers and non-denim garments',
                'compliance' => true,
                'leed' => null,
                'capacity' => '700,000 pcs/month',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'SM Knitwear Ltd.',
                'category' => 'Knit',
                'specialization' => 'T-shirts, polos, sweatshirts, hoodies, pants, jackets, leggings and dresses',
                'compliance' => true,
                'leed' => null,
                'capacity' => 'Cutting capacity: 4-4.5 million pcs/month',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Shin Shin Group',
                'category' => 'Woven',
                'specialization' => 'Denim garments and fashion woven products',
                'compliance' => true,
                'leed' => 'Gold',
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Knit Asia Ltd.',
                'category' => 'Knit',
                'specialization' => 'Performance wear, seamless garments, denim, intimates and jacquard sweaters',
                'compliance' => true,
                'leed' => 'Platinum',
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Farseeing Knit Composite Ltd.',
                'category' => 'Woven',
                'specialization' => 'Shirts, blouses, boxers, pajamas, palazzos, shackets and sleepwear',
                'compliance' => false,
                'leed' => null,
                'capacity' => '500,000 units; period not specified',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Pastel',
                'category' => 'Woven',
                'specialization' => 'Woven fashion garments',
                'compliance' => true,
                'leed' => null,
                'capacity' => '250,000 pcs/month',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Interfab Shirt Manufacturing Ltd.',
                'category' => 'Woven',
                'specialization' => 'Formal shirts, casual shirts, blouses, dresses, shackets, overshirts and schoolwear',
                'compliance' => true,
                'leed' => null,
                'capacity' => '350,000 pcs/month',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'ACS Textiles (BD) Ltd.',
                'category' => 'Home Textile',
                'specialization' => 'Bed linen, bedding, bath linen and towels',
                'compliance' => true,
                'leed' => null,
                'capacity' => null,
                'is_active' => true,
                'sort_order' => 22,
            ],
        ];

        foreach ($factories as $factory) {
            FactoryPartner::query()->updateOrCreate(
                [
                    'name' => $factory['name'],
                ],
                $factory
            );
        }
    }
}